In [91]:
import numpy as np

# Numpy Arrays.

In [92]:
my_list = [1, 2, 3]

In [93]:
# Converts a 1d list to a numpy vector.
np.array(my_list)

array([1, 2, 3])

In [94]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [95]:
# Converts a 2d list to a numpy matrix.
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
# Returns evenly spaced values within a given interval.
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [97]:
# Returns a matrix or a vector full of zeros depending on the dimensions given.
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [98]:
# Returns evenly spaced numbers over a specified interval. (i.e. 50 elements from 0 to 10 in this case.)
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [99]:
# Returns Identity Matrix.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [100]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].
np.random.rand(5,5)

array([[0.3937301 , 0.66667385, 0.78901421, 0.50307142, 0.27350302],
       [0.69991138, 0.85030373, 0.84957589, 0.86634934, 0.16303612],
       [0.47695319, 0.57269826, 0.78980688, 0.12842153, 0.65984128],
       [0.48199915, 0.6925324 , 0.26868261, 0.69321183, 0.03330802],
       [0.32385228, 0.73116682, 0.22877735, 0.25449347, 0.05470188]])

In [101]:
# Returns a sample (or samples) from the "standard normal" distribution.
np.random.randn(5,5)

array([[-0.55712777, -0.67346744, -1.70634376,  1.10354523, -0.33480225],
       [-0.70057146, -0.19877186,  1.06497318,  1.1491491 , -0.88331917],
       [-1.44516524, -0.92716834,  1.33361402,  1.04181398, -1.43849769],
       [-1.29624198, -0.50700399,  0.79829655,  0.02373134, -0.06348288],
       [-1.11902555,  0.25517391, -0.6950749 ,  0.02489072,  0.82332654]])

In [102]:
# Returns random integers from low (inclusive) to high (exclusive) also you can specify the amount of elements.
np.random.randint(1,100,10)

array([37, 19,  8,  4, 64, 82, 85, 84,  5, 85])

In [103]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [104]:
# Could reshape a 1d vector to a 2d matrix as long as the number of elements in both are the same.
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
# min value and max value in a numpy array.
ranarr_max = ranarr.max()
ranarr_min = ranarr.min()

In [106]:
# the indicies of both the max element and min element in an array
max_index = ranarr.argmax()
min_index = ranarr.argmin()

In [107]:
# size of the numpy vector or matrix.
arr.shape

(25,)

# Numpy Indexing and Selection

In [108]:
arr = np.arange(0,11)
# Setting a value with index range (Broadcasting, can not be done in a normal python list).
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [109]:
# If you take a slice of a numpy array it is not a copy if it changes the main array changes too.(Use arr.copy() to get a copy)
slice_of_arr = arr[0:6]
slice_of_arr[:] = 200
arr

array([200, 200, 200, 200, 200, 200,   6,   7,   8,   9,  10])

In [110]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [111]:
# slicing a box from the 2d numpy matrix.
arr2d_slice = arr_2d[:2, 1:]
arr2d_slice

array([[10, 15],
       [25, 30]])

In [112]:
arr

array([200, 200, 200, 200, 200, 200,   6,   7,   8,   9,  10])

In [114]:
# Filter the array with the values that are less than 200.
arr = arr[arr < 200]
arr

array([ 6,  7,  8,  9, 10])

# Numpy Operations.

In [115]:
arr

array([ 6,  7,  8,  9, 10])

In [119]:
# can use all kinds of math operations on array with another array and array with a scalar
arr_arr = arr * arr
arr_scalar = arr * 5

In [121]:
# There are some other universal math operations that could be used on numpy arrays.
arr_sqr = np.sqrt(arr) # could also be done by using(arr_sqr = arr ** 2)
arr_exp = np.exp(arr)